exports.up = knex => knex.schema.createTable('fornecedor', table => {
    table.increments('for_cod',100)
    table.string('for_nome',100)
    table.string('for_rsocial',100)
    table.string('for_ie',100)
    table.string('for_cnpj',100)
    table.string('for_cep',100)
    table.string('for_endereco',100)
    table.string('for_bairro',100)
    table.string('for_fone',100)
    table.string('for_cel',100)
    table.string('for_email',100)
    table.string('for_endnumero',100)
    table.string('for_cidade',100)
    table.string('for_estado',100)
    table.timestamps(true, true)
})

exports.down = knex => knex.schema.dropTable('fornecedor')