exports.up = knex=> knex.schema.createTable('cliente', table=>{
    table.increments('cli_cod')
    table.string('cli_nome',100)   
    table.string('cli_cpfcnpj',20)   
    table.string('cli_rgie',30)   
    table.string('cli_rsocial',100)   
    table.string('cli_tipo',100)   
    table.string('cli_cep',30)   
    table.string('cli_endereco',100)   
    table.string('cli_bairro',100)   
    table.string('cli_fone',50)   
    table.string('cli_cel',50)   
    table.string('cli_endnumero',10)   
    table.string('cli_email',100)   
    table.string('cli_cidade',60)   
    table.string('cli_estado',60)   
    table.timestamps(true,true)
})

exports.down = knex=> knex.schema.dropTable('cliente')